quarkus:
  application:
    name: product-service
  http:
    port: 8012
  
  # Logging configuration
  log:
    level: INFO
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      level: INFO
  
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    reactive:
      url: postgresql://localhost:5432/product_db
  
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  
  devservices:
    enabled: false
  
  kafka:
    devservices:
      enabled: false
  
  swagger-ui:
    always-include: true
  
  smallrye-openapi:
    path: /openapi

mp:
  messaging:
    connector:
      smallrye-kafka:
        bootstrap:
          servers: localhost:29092
    
    outgoing:
      audit-crud:
        connector: smallrye-kafka
        topic: audit.crud
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
      
      audit-error:
        connector: smallrye-kafka
        topic: audit.error
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
